### ISSUE TITLE
第三章的admin.py 在python3.6下运行错误

### ISSUE THREAD

**Issue by hurricane1988** [the5fire/django-practice-book#18]
原文代码：
fieldsets = (
        (None, {
         'fields': (
                 'name',
                 ('sex', 'profession'),
                 ('email', 'qq', 'phone'),
                 'status',
                 )
         }),
    )
应修改为
fieldsets = [
        (None, {
            'fields': (
                'name',
                ('sex', 'profession'),
                ('email', 'qq', 'phone'),
                'status',
            )
        })
    ]
不然会直接报错误：
 (admin.E008) The value of 'fieldsets[0]' must be a list or tuple

**Comment by the5fire** [comment]
有问题还可以再次打开 Issue
