### ISSUE TITLE
勘误：第 1 版第 1 次印刷，123页，6.2.4 节

### ISSUE THREAD

**Issue by jpch89** [the5fire/django-practice-book#28]
第一段代码上面的文字：
> 我们通过 Form 来定制 status 这个字段的展示：

此处笔误，与下面代码对照，改的是 `desc` 字段而不是 `status`，所以应改为：
> 我们通过 Form 来定制 desc 这个字段的展示：

**Comment by the5fire** [comment]
确实如此，十分感谢！！
