### ISSUE TITLE
[勘误]第一章P10页

### ISSUE THREAD

**Issue by panxingj** [the5fire/django-practice-book#31]
图1-1，SideBar中，created_time的字段类型不应该为str，应该为datetime类型！
本书中所有这张关系图中的SideBar的created_time字段类型都是错的！

**Comment by the5fire** [comment]
确实标记错了，感谢反馈！

**Comment by panxingj** [comment]
您好，我看到您的网站上已经登出勘误了，可是应该是created_time字段，而不是datetime字段，created_time的字段**类型**为datetime！
