### ISSUE TITLE
第3章 测试代码敲好了，如何进行代码测试

### ISSUE THREAD

**Issue by jeckun** [the5fire/django-practice-book#7]
按照3.4.3章节提示，在test.py 中添加了StudentTestCase类和各个函数的代码。

可是并没有找到如何进行测试的方法，请问我该如何进行测试。

我的环境是: Mac + python3.6 + django2.1.7 + PyCharm2018.3

**Comment by the5fire** [comment]
```python manage.py test```
: https://docs.djangoproject.com/en/2.1/intro/tutorial05/#running-tests

**Comment by jeckun** [comment]
谢谢，我试一下。
