### ISSUE TITLE
[勘误]第11章 243页 content 属性问题

### ISSUE THREAD

**Issue by Yangzhedi** [the5fire/django-practice-book#8]
之前第5章的例子里  Post类正文的属性是`content`
但是到了11章 237 页 11.1.1 和 243页 11.2 的代码里就变成了`content_html`了

**Comment by the5fire** [comment]
你可能跳过了 第九章 - 9.4 - 199页。
一开始只有普通的 content，后面引入了 Markdown 格式，所以需要另外一个字段来存储原始文本，另外一个字段存储转为 html 的内容。

**Comment by Yangzhedi** [comment]
> 你可能跳过了 第九章 - 9.4 - 199页。
> 一开始只有普通的 content，后面引入了 Markdown 格式，所以需要另外一个字段来存储原始文本，另外一个字段存储转为 html 的内容。

哦哦  原来如此
